'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/components/auth/auth-provider';
import { testApi, subjectApi } from '@/lib/api';
import { Skeleton } from '@/components/ui/Skeleton';
import styles from './tests.module.css';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

export default function PracticeTestsPage() {
  const router = useRouter();
  const { user } = useAuth();
  const [subjects, setSubjects] = useState<any[]>([]);
  const [selectedSubject, setSelectedSubject] = useState('');
  const [topic, setTopic] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [test, setTest] = useState<any>(null);
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const [result, setResult] = useState<any>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [timeLeft, setTimeLeft] = useState(600);
  const [history, setHistory] = useState<any[]>([]);
  
  const totalTime = 600;

  useEffect(() => {
    if (user) {
      subjectApi.getSubjects().then(setSubjects).catch(console.error);
      testApi.getHistory().then(setHistory).catch(console.error);
    }
  }, [user]);

  useEffect(() => {
    let timer: any;
    if (test && !result && timeLeft > 0) {
      timer = setInterval(() => setTimeLeft(prev => prev - 1), 1000);
    } else if (timeLeft === 0 && test && !result) {
      handleSubmitTest();
    }
    return () => clearInterval(timer);
  }, [test, result, timeLeft]);

  const handleGenerateTest = async () => {
    if (!selectedSubject || !topic) return;
    setIsGenerating(true);
    setTest(null);
    setResult(null);

    try {
      const data = await testApi.generate({ subject_id: selectedSubject, topic });
      setTest(data);
      setAnswers({});
      setTimeLeft(600);
    } catch (err) {
      alert('Failed to generate test.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSubmitTest = async () => {
    if (!test || result || isSubmitting) return;
    
    setIsSubmitting(true);
    try {
      const data = await testApi.submit(test.id, answers);
      setResult(data);
      testApi.getHistory().then(setHistory).catch(console.error);
    } catch (err) {
      alert('Failed to submit test');
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!user) return null;

  const dashOffset = 251.2 - (251.2 * timeLeft) / totalTime;

  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1 className={styles.title}>AI Practice <span>Engine</span></h1>
        <p className={styles.subtitle}>Test your logic with personalized assessments generated by Gemini 1.5 Pro.</p>
      </header>

      {history.length > 0 && !test && !result && (
        <section className={`${styles.historyCard} glass`} style={{ marginBottom: '40px', padding: '30px', borderRadius: '32px' }}>
          <h3 style={{ marginBottom: '20px' }}>Performance Trajectory</h3>
          <div style={{ width: '100%', height: '200px' }}>
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={history.slice(-10)}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                <XAxis dataKey="created_at" hide />
                <YAxis stroke="rgba(255,255,255,0.4)" fontSize={12} />
                <Tooltip 
                  contentStyle={{ background: '#1a1a2e', border: '1px solid #333', borderRadius: '12px' }}
                  labelStyle={{ display: 'none' }}
                />
                <Line type="monotone" dataKey="score" stroke="#7c3aed" strokeWidth={3} dot={{ fill: '#7c3aed', r: 4 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </section>
      )}

      {!test && !result && (
        <section className={`${styles.generatorCard} glass`}>
          <div className={styles.inputGroup}>
            <label>Academic Subject</label>
            <select 
              className={styles.select}
              value={selectedSubject}
              onChange={(e) => setSelectedSubject(e.target.value)}
            >
              <option value="">Select a subject...</option>
              {subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          </div>
          <div className={styles.inputGroup}>
            <label>Specific Topic</label>
            <input 
              className={styles.input}
              type="text" 
              placeholder="e.g. CPU Scheduling" 
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
            />
          </div>
          <button 
            className={styles.generateBtn} 
            onClick={handleGenerateTest}
            disabled={isGenerating || !selectedSubject || !topic}
          >
            {isGenerating ? 'Synthesizing Quiz...' : 'Generate AI Test'}
          </button>
        </section>
      )}

      {test && !result && (
        <section className={styles.testArea}>
          <div className={`${styles.testHeader} glass`}>
            <div>
              <div className={styles.subjectTag}>{subjects.find(s => s.id === test.subject_id)?.name}</div>
              <h2 className={styles.testTopic}>{test.topic}</h2>
            </div>
            <div className={styles.circularTimer}>
              <svg width="60" height="60" viewBox="0 0 100 100">
                <circle cx="50" cy="50" r="40" stroke="rgba(255,255,255,0.1)" strokeWidth="8" fill="none" />
                <circle 
                  cx="50" cy="50" r="40" 
                  stroke={timeLeft < 60 ? "#ef4444" : "#7c3aed"} 
                  strokeWidth="8" 
                  fill="none" 
                  strokeDasharray="251.2"
                  strokeDashoffset={dashOffset}
                  strokeLinecap="round"
                  style={{ transition: 'stroke-dashoffset 1s linear' }}
                />
                <text x="50" y="58" textAnchor="middle" fill="white" fontWeight="800" fontSize="22">
                  {Math.floor(timeLeft / 60)}:{(timeLeft % 60).toString().padStart(2, '0')}
                </text>
              </svg>
            </div>
          </div>

          <div className={styles.questionGrid}>
            {test.questions.map((q: any, qIdx: number) => (
              <div key={q.id || qIdx} className={`${styles.questionCard} glass`}>
                <p className={styles.questionText}><strong>Q{qIdx + 1}.</strong> {q.question_text}</p>
                <div className={styles.optionGrid}>
                  {q.options.map((opt: string, optIdx: number) => (
                    <button 
                      key={optIdx} 
                      className={`${styles.optBtn} ${answers[q.id] === optIdx ? styles.selected : ''}`}
                      onClick={() => setAnswers({...answers, [q.id]: optIdx})}
                    >
                      {opt}
                    </button>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className={styles.testFooter}>
            <button className="sb-btnPrimary" onClick={handleSubmitTest} disabled={isSubmitting} style={{ width: '100%', border: 'none' }}>
              {isSubmitting ? 'Evaluating Performance...' : 'Submit Assessment'}
            </button>
          </div>
        </section>
      )}

      {result && (
        <section className={`${styles.resultCard} glass`}>
          <div className={styles.resultHeader}>
            <div className={styles.scoreCircle}>
              <span className={styles.scoreNumber}>{result.score}%</span>
            </div>
            <div>
              <h2>{result.score >= 80 ? 'Mastery Achieved!' : 'Growth Needed'}</h2>
              <p>You earned <strong>+{result.pointsEarned || 5} XP</strong> for this attempt.</p>
            </div>
          </div>
          <button className={styles.resetBtn} onClick={() => { setTest(null); setResult(null); }}>Take Another Test</button>
        </section>
      )}
    </div>
  );
}
