'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/components/auth/auth-provider';
import { testApi, subjectApi } from '@/lib/api';
import { Skeleton } from '@/components/ui/Skeleton';
import styles from './tests.module.css';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { BrainCircuit, Lock, ArrowRight } from 'lucide-react';

export default function PracticeTestsPage() {
  const router = useRouter();
  const { user } = useAuth();
  const [subjects, setSubjects] = useState<any[]>([]);
  const [selectedSubject, setSelectedSubject] = useState('');
  const [topic, setTopic] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [test, setTest] = useState<any>(null);
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const [result, setResult] = useState<any>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [timeLeft, setTimeLeft] = useState(600);
  const [history, setHistory] = useState<any[]>([]);

  const totalTime = 600;

  useEffect(() => {
    if (user) {
      subjectApi.getSubjects().then(setSubjects).catch(console.error);
      testApi.getHistory().then(setHistory).catch(console.error);
    }
  }, [user]);

  useEffect(() => {
    let timer: any;
    if (test && !result && timeLeft > 0) {
      timer = setInterval(() => setTimeLeft(prev => prev - 1), 1000);
    } else if (timeLeft === 0 && test && !result) {
      handleSubmitTest();
    }
    return () => clearInterval(timer);
  }, [test, result, timeLeft]);

  const handleGenerateTest = async () => {
    if (!selectedSubject || !topic) return;
    setIsGenerating(true);
    setTest(null);
    setResult(null);
    try {
      const data = await testApi.generate({ subject_id: selectedSubject, topic });
      setTest(data);
      setAnswers({});
      setTimeLeft(600);
    } catch (err) {
      alert('Failed to generate test.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSubmitTest = async () => {
    if (!test || result || isSubmitting) return;
    setIsSubmitting(true);
    try {
      const data = await testApi.submit(test.id, answers);
      setResult(data);
      testApi.getHistory().then(setHistory).catch(console.error);
    } catch (err) {
      alert('Failed to submit test');
    } finally {
      setIsSubmitting(false);
    }
  };

  const dashOffset = 251.2 - (251.2 * timeLeft) / totalTime;

  // Show login prompt for unauthenticated users
  if (!user) {
    return (
      <div className="min-h-screen bg-[#09090f] flex items-center justify-center px-4">
        <div className="text-center max-w-md">
          <div className="w-20 h-20 rounded-2xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center mx-auto mb-6">
            <BrainCircuit className="w-10 h-10 text-purple-400" />
          </div>
          <h1 className="text-3xl font-black text-white mb-3">AI Practice Engine</h1>
          <p className="text-gray-400 mb-2">Test your logic with personalized AI-generated assessments.</p>
          <div className="flex items-center justify-center gap-2 text-amber-400 text-sm mb-8">
            <Lock className="w-4 h-4" />
            <span>Sign in to unlock unlimited practice tests</span>
          </div>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Link
              href="/auth"
              className="flex items-center justify-center gap-2 bg-purple-600 hover:bg-purple-500 text-white font-bold px-6 py-3 rounded-xl transition-all"
            >
              Sign In to Start <ArrowRight className="w-4 h-4" />
            </Link>
            <Link
              href="/"
              className="flex items-center justify-center gap-2 bg-white/5 hover:bg-white/10 text-gray-300 font-medium px-6 py-3 rounded-xl border border-white/10 transition-all"
            >
              Learn More
            </Link>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h1 className={styles.title}>AI Practice <span className={styles.accent}>Engine</span></h1>
        <p className={styles.subtitle}>Test your logic with personalized assessments generated by Gemini 1.5 Pro.</p>
      </div>

      {history.length > 0 && !test && !result && (
        <section className={styles.historySection}>
          <h3 className={styles.sectionTitle}>Performance Trajectory</h3>
          <ResponsiveContainer width="100%" height={200}>
            <LineChart data={history.slice(0, 10).reverse()}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
              <XAxis dataKey="topic" tick={{ fill: '#9ca3af', fontSize: 11 }} />
              <YAxis tick={{ fill: '#9ca3af', fontSize: 11 }} />
              <Tooltip contentStyle={{ background: '#1a1a2e', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px' }} />
              <Line type="monotone" dataKey="score" stroke="#7c3aed" strokeWidth={2} dot={{ fill: '#7c3aed' }} />
            </LineChart>
          </ResponsiveContainer>
        </section>
      )}

      {!test && !result && (
        <section className={styles.generateSection}>
          <div className={styles.formGroup}>
            <label className={styles.label}>Academic Subject</label>
            <select className={styles.select} value={selectedSubject} onChange={(e) => setSelectedSubject(e.target.value)}>
              <option value="">Select a subject...</option>
              {subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          </div>
          <div className={styles.formGroup}>
            <label className={styles.label}>Specific Topic</label>
            <input className={styles.input} type="text" placeholder="e.g. CPU Scheduling" value={topic} onChange={(e) => setTopic(e.target.value)} />
          </div>
          <button className={styles.generateBtn} onClick={handleGenerateTest} disabled={!selectedSubject || !topic || isGenerating}>
            {isGenerating ? 'Synthesizing Quiz...' : 'Generate AI Test'}
          </button>
        </section>
      )}

      {test && !result && (
        <section className={styles.testSection}>
          <div className={styles.testHeader}>
            <div>
              <span className={styles.subjectTag}>{subjects.find(s => s.id === test.subject_id)?.name}</span>
              <h2 className={styles.testTopic}>{test.topic}</h2>
            </div>
            <div className={styles.timerContainer}>
              <svg viewBox="0 0 100 100" className={styles.timerSvg}>
                <circle cx="50" cy="50" r="40" fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="8" />
                <circle cx="50" cy="50" r="40" fill="none" stroke="#7c3aed" strokeWidth="8"
                  strokeDasharray="251.2" strokeDashoffset={dashOffset}
                  strokeLinecap="round" transform="rotate(-90 50 50)" />
              </svg>
              <span className={styles.timerText}>{Math.floor(timeLeft / 60)}:{(timeLeft % 60).toString().padStart(2, '0')}</span>
            </div>
          </div>
          {test.questions.map((q: any, qIdx: number) => (
            <div key={q.id} className={styles.questionCard}>
              <p className={styles.questionText}><strong>Q{qIdx + 1}.</strong> {q.question_text}</p>
              <div className={styles.options}>
                {q.options.map((opt: string, optIdx: number) => (
                  <button key={optIdx} className={`${styles.option} ${answers[q.id] === optIdx ? styles.selected : ''}`}
                    onClick={() => setAnswers({...answers, [q.id]: optIdx})}>{opt}</button>
                ))}
              </div>
            </div>
          ))}
          <button className={styles.submitBtn} onClick={handleSubmitTest} disabled={isSubmitting}>
            {isSubmitting ? 'Evaluating Performance...' : 'Submit Assessment'}
          </button>
        </section>
      )}

      {result && (
        <section className={`${styles.resultCard} glass`}>
          <div className={styles.resultHeader}>
            <div className={styles.scoreCircle}>
              <span className={styles.scoreNumber}>{result.score}%</span>
            </div>
            <div>
              <h2>{result.score >= 80 ? 'Mastery Achieved!' : 'Growth Needed'}</h2>
              <p>You earned <strong>+{result.pointsEarned || 5} XP</strong> for this attempt.</p>
            </div>
          </div>
          <button className={styles.resetBtn} onClick={() => { setTest(null); setResult(null); }}>Take Another Test</button>
        </section>
      )}
    </div>
  );
}
