import PracticeTestsPageClient from './PracticeTestsPageClient';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'AI Practice Engine | DEV_FUSION',
  description: 'Test your logic with personalized assessments generated by Gemini 1.5 Pro.',
  openGraph: {
    title: 'AI Practice Engine | DEV_FUSION',
    description: 'Test your logic with personalized assessments generated by Gemini 1.5 Pro.',
    type: 'website'
  }
};

export default function PracticeTestsPage() {
  return <PracticeTestsPageClient />;
}
