'use client';

import { useState, useEffect, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/components/auth/auth-provider';
import { testApi, subjectApi } from '@/lib/api';
import { Skeleton } from '@/components/ui/Skeleton';
import styles from './tests.module.css';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { BrainCircuit, Lock, ArrowRight } from 'lucide-react';

export default function PracticeTestsPageClient() {
  const router = useRouter();
  const { user } = useAuth();
  const [subjects, setSubjects] = useState<any[]>([]);
  const [selectedSubject, setSelectedSubject] = useState('');
  const [topic, setTopic] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [test, setTest] = useState<any>(null);
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const [result, setResult] = useState<any>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [timeLeft, setTimeLeft] = useState(600);
  const [history, setHistory] = useState<any[]>([]);

  const totalTime = 600;

  useEffect(() => {
    if (user) {
      subjectApi.getSubjects().then(setSubjects).catch(console.error);
      testApi.getHistory().then(setHistory).catch(console.error);
    }
  }, [user]);

  const handleSubmitTest = useCallback(async () => {
    if (!test || result || isSubmitting) return;
    setIsSubmitting(true);
    try {
      const data = await testApi.submit(test.id, answers);
      setResult(data);
      testApi.getHistory().then(setHistory).catch(console.error);
    } catch (err) {
      alert('Failed to submit test');
    } finally {
      setIsSubmitting(false);
    }
  }, [test, result, isSubmitting, answers]);

  useEffect(() => {
    let timer: any;
    if (test && !result && timeLeft > 0) {
      timer = setInterval(() => setTimeLeft(prev => prev - 1), 1000);
    } else if (timeLeft === 0 && test && !result) {
      handleSubmitTest();
    }
    return () => clearInterval(timer);
  }, [test, result, timeLeft, handleSubmitTest]);

  const handleGenerateTest = async () => {
    if (!selectedSubject || !topic) return;
    setIsGenerating(true);
    setTest(null);
    setResult(null);
    try {
      const data = await testApi.generate({ subject_id: selectedSubject, topic });
      setTest(data);
      setAnswers({});
      setTimeLeft(600);
    } catch (err) {
      alert('Failed to generate test.');
    } finally {
      setIsGenerating(false);
    }
  };

  const dashOffset = 251.2 - (251.2 * timeLeft) / totalTime;

  if (!user) {
    return (
      <div className="min-h-screen bg-[#0a0a1a] flex flex-col items-center justify-center px-4 py-20">
        <div className="text-center max-w-lg">
          <div className="flex justify-center mb-6">
            <div className="p-4 rounded-2xl bg-indigo-500/10 border border-indigo-500/20">
              <BrainCircuit className="w-12 h-12 text-indigo-400" />
            </div>
          </div>
          <h1 className="text-4xl font-bold text-white mb-4">AI Practice Engine</h1>
          <p className="text-gray-400 text-lg mb-4">Test your logic with personalized AI-generated assessments.</p>
          <div className="flex items-center justify-center gap-2 text-gray-500 mb-8">
            <Lock className="w-4 h-4" />
            <span>Sign in to unlock unlimited practice tests</span>
          </div>
          <Link
            href="/auth"
            className="inline-flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold px-8 py-3 rounded-xl transition-colors"
          >
            Sign In to Start <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0a0a1a] px-4 py-10 max-w-4xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white mb-2">AI Practice <span className="text-indigo-400">Engine</span></h1>
        <p className="text-gray-400">Test your logic with personalized assessments generated by Gemini 1.5 Pro.</p>
      </div>

      {history.length > 0 && !test && !result && (
        <div className="mb-8 p-6 rounded-2xl bg-white/5 border border-white/10">
          <h3 className="text-white font-semibold mb-4">Performance Trajectory</h3>
          <ResponsiveContainer width="100%" height={160}>
            <LineChart data={history.slice(-10).reverse()}>
              <CartesianGrid strokeDasharray="3 3" stroke="#ffffff10" />
              <XAxis dataKey="topic" hide />
              <YAxis domain={[0, 100]} stroke="#6366f1" />
              <Tooltip contentStyle={{ background: '#1e1e3f', border: 'none', color: '#fff' }} />
              <Line type="monotone" dataKey="score" stroke="#6366f1" strokeWidth={2} dot={{ fill: '#6366f1' }} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      )}

      {!test && !result && (
        <div className="p-6 rounded-2xl bg-white/5 border border-white/10 mb-6">
          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-300 mb-2">Academic Subject</label>
            <select
              className={styles.select}
              value={selectedSubject}
              onChange={(e) => setSelectedSubject(e.target.value)}
            >
              <option value="">Select a subject...</option>
              {subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          </div>
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-300 mb-2">Specific Topic</label>
            <input
              className={styles.input}
              type="text"
              placeholder="e.g. CPU Scheduling"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
            />
          </div>
          <button
            onClick={handleGenerateTest}
            disabled={!selectedSubject || !topic || isGenerating}
            className="w-full bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-semibold py-3 rounded-xl transition-colors"
          >
            {isGenerating ? 'Synthesizing Quiz...' : 'Generate AI Test'}
          </button>
        </div>
      )}

      {test && !result && (
        <div className="space-y-6">
          <div className="flex items-center justify-between p-4 rounded-xl bg-white/5 border border-white/10">
            <div>
              <span className="text-xs text-indigo-400 font-medium">{subjects.find(s => s.id === test.subject_id)?.name}</span>
              <h2 className="text-xl font-bold text-white">{test.topic}</h2>
            </div>
            <div className="text-center">
              <div className="text-2xl font-mono font-bold text-indigo-400">
                {Math.floor(timeLeft / 60)}:{(timeLeft % 60).toString().padStart(2, '0')}
              </div>
            </div>
          </div>

          {test.questions.map((q: any, qIdx: number) => (
            <div key={q.id} className="p-6 rounded-2xl bg-white/5 border border-white/10">
              <p className="text-white font-medium mb-4"><strong>Q{qIdx + 1}.</strong> {q.question_text}</p>
              <div className="space-y-2">
                {q.options.map((opt: string, optIdx: number) => (
                  <button
                    key={optIdx}
                    onClick={() => setAnswers({...answers, [q.id]: optIdx})}
                    className={`w-full text-left px-4 py-3 rounded-xl border transition-colors ${
                      answers[q.id] === optIdx
                        ? 'bg-indigo-600/30 border-indigo-500 text-white'
                        : 'bg-white/5 border-white/10 text-gray-300 hover:bg-white/10'
                    }`}
                  >{opt}</button>
                ))}
              </div>
            </div>
          ))}

          <button
            onClick={handleSubmitTest}
            disabled={isSubmitting}
            className="w-full bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white font-semibold py-3 rounded-xl transition-colors"
          >
            {isSubmitting ? 'Evaluating Performance...' : 'Submit Assessment'}
          </button>
        </div>
      )}

      {result && (
        <div className="p-8 rounded-2xl bg-white/5 border border-white/10 text-center">
          <div className="text-6xl font-bold text-indigo-400 mb-2">{result.score}%</div>
          <h2 className="text-2xl font-bold text-white mb-2">{result.score >= 80 ? 'Mastery Achieved!' : 'Growth Needed'}</h2>
          <p className="text-gray-400 mb-6">You earned <strong className="text-indigo-400">+{result.pointsEarned || 5} XP</strong> for this attempt.</p>
          <button
            onClick={() => { setTest(null); setResult(null); }}
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-semibold px-8 py-3 rounded-xl transition-colors"
          >Take Another Test</button>
        </div>
      )}
    </div>
  );
}
